#include <iostream>
using namespace std;
main() {
cout<<"Number 1:";
int number1;
cin>>number1;
cout<<"Number 2:";
int number2;
cin>>number2;
cout<<"Number 3:";
int number3;
cin>>number3;
cout<<"Number 4:";
int number4;
cin>>number4;
cout<<"Number 5:";
int number5;
cin>>number5;
cout<<"Number 6:";
int number6;
cin>>number6;
cout<<"Number 7:";
int number7;
cin>>number7;
cout<<"Number 8:";
int number8;
cin>>number8;
cout<<"Number 9:";
int number9;
cin>>number9;
cout<<"Number 10:";
int number10;
cin>>number10;
cout<<"Number 11:";
int number11;
cin>>number11;
cout<<"Number 12:";
int number12;
cin>>number12;
cout<<"Number 13:";
int number13;
cin>>number13;
cout<<"Number 14:";
int number14;
cin>>number14;
cout<<"Number 15:";
int number15;
cin>>number15;
int first_5_number_sum;
int sum=number1+number2+number3+number4+number5;
int first_5_number_multiply;
int multiply=number6*number7*number8*number9*number10;
int first_5_number_subtract;
int subtract=number11-number12-number13-number14-number15;
int result;
result=(sum)+(multiply)-(subtract);
cout<<"The final results is: " <<result;
}
